services:
  - type: web
    name: AIwebsite-genstl
    rootDir: AIGenSTL
    env: python
    region: oregon
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gthread --workers 1 --threads 4 --timeout 180 app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DOUBAO_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
